"""Deploy Lustre staging tree to a running VM.

Shared by single-node deploy (cli.py cmd_deploy) and
multi-node cluster deploy (vm_cluster.py).
"""

from __future__ import annotations

import shlex
import subprocess
import sys
from pathlib import Path

from .vm_state import (
    EXIT_ERROR,
    EXIT_NOT_FOUND,
    ROOT_PASSWORD,
    VMInfo,
    VMNotFound,
    lustre_libdir,
)
from .vm_net import run_ssh


def deploy_to_vm(
    vm: VMInfo,
    staging: Path,
    *,
    os_family: str = "rhel",
    userspace_only: bool = False,
) -> None:
    """Stream a Lustre staging tree into a VM.

    1. tar | ssh the staging dir into /
    2. depmod + ldconfig
    3. Configure test disk mappings in cfg/local.sh

    Raises RuntimeError on failure.
    """
    if not staging.is_dir():
        raise RuntimeError(f"Staging directory not found: {staging}")

    # Stream staging tree into the VM, unpacking directly into /.
    # --userspace-only: exclude lib/modules/ so kernel modules already in
    # the VM are not overwritten (and depmod is skipped below).
    exclude_modules = "--exclude=./lib/modules" if userspace_only else ""
    tar_cmd = (
        f"set -o pipefail; "
        f"tar cf - -C {shlex.quote(str(staging))} {exclude_modules} . "
        f"| sshpass -p {shlex.quote(ROOT_PASSWORD)} ssh "
        f"-o StrictHostKeyChecking=no -o LogLevel=ERROR "
        f"root@{shlex.quote(vm.ip)} "
        f"'tar xf - -C / --keep-directory-symlink --no-same-owner'"
    )
    r = subprocess.run(
        ["bash", "-c", tar_cmd], capture_output=True, text=True, timeout=120
    )
    if r.returncode != 0:
        output = (r.stdout or "") + (r.stderr or "")
        raise RuntimeError(f"tar deploy failed: {output.strip()}")

    # depmod + ldconfig to pick up new modules and libraries.
    post_deploy_cmd = "ldconfig" if userspace_only else "depmod -a && ldconfig"
    r = run_ssh(vm.ip, post_deploy_cmd, timeout=60)
    if r.returncode != 0:
        raise RuntimeError(
            f"post-deploy ({post_deploy_cmd}) failed "
            f"(rc={r.returncode}): {r.stderr}"
        )

    # Configure test framework's local.sh with VM disk topology
    if vm.mdt_disks or vm.ost_disks:
        configure_test_disks(
            vm.ip, vm.mdt_disks, vm.ost_disks, vm.disk_size,
            os_family=os_family,
        )


def configure_test_disks(
    ip: str, mdt_disks: int, ost_disks: int,
    disk_size_bytes: int = 0, os_family: str = "rhel",
) -> None:
    """Write OSTCOUNT/OSTDEV*/MDSCOUNT/MDSDEV*/OSTSIZE into cfg/local.sh.

    Virtio disks are attached in order (MDT first, then OST),
    starting at /dev/vdb (vda = rootfs).
    """
    testdir = f"{lustre_libdir(os_family)}/tests"
    lines = []

    # Set device sizes in KB (test framework uses KB for OSTSIZE/MDSSIZE)
    if disk_size_bytes:
        size_kb = disk_size_bytes // 1024
        if mdt_disks:
            lines.append(f"MDSSIZE={size_kb}")
        if ost_disks:
            lines.append(f"OSTSIZE={size_kb}")

    if mdt_disks:
        lines.append(f"MDSCOUNT={mdt_disks}")
        for n in range(1, mdt_disks + 1):
            letter = chr(ord('a') + n)
            lines.append(f"MDSDEV{n}=/dev/vd{letter}")

    if ost_disks:
        lines.append(f"OSTCOUNT={ost_disks}")
        for n in range(1, ost_disks + 1):
            letter = chr(ord('a') + mdt_disks + n)
            lines.append(f"OSTDEV{n}=/dev/vd{letter}")

    snippet = "\\n".join(lines)
    script = (
        f"sed -i '/^# --- VM disk configuration/,/^# --- END VM disk/d' "
        f"{testdir}/cfg/local.sh 2>/dev/null || true; "
        f"printf '\\n# --- VM disk configuration (generated by ltvm deploy) ---\\n"
        f"{snippet}\\n"
        f"# --- END VM disk configuration ---\\n' >> {testdir}/cfg/local.sh"
    )
    r = run_ssh(ip, script, timeout=30)
    if r.returncode != 0:
        raise RuntimeError(
            f"Failed to configure test disks in {testdir}/cfg/local.sh: "
            f"{r.stderr.strip()}"
        )


def lustre_mount_vm(name: str, os_family: str) -> int:
    """Run llmount.sh inside a VM. Returns exit code."""
    try:
        vm = VMInfo.load(name)
    except VMNotFound as e:
        print(f"error: {e}", file=sys.stderr)
        return EXIT_NOT_FOUND
    libdir = lustre_libdir(os_family)
    try:
        # Clean up any existing Lustre state before formatting.  llmount.sh
        # runs its own stopall internally, but does not call dmsetup remove_all
        # afterward, so mke2fs refuses to reformat backing devices that are
        # still "in use" by leftover dm targets on re-deploy.
        run_ssh(
            vm.ip,
            f"cd {libdir}/tests && LUSTRE={libdir} bash llmountcleanup.sh 2>/dev/null; "
            "lustre_rmmod 2>/dev/null; dmsetup remove_all 2>/dev/null; true",
            timeout=60,
        )
        r = run_ssh(
            vm.ip,
            f"cd {libdir}/tests && LUSTRE={libdir} bash llmount.sh",
            timeout=180,
        )
        if r.stdout:
            print(r.stdout, end="")
        if r.stderr:
            print(r.stderr, end="", file=sys.stderr)
        return r.returncode
    except Exception as e:
        print(f"error: Lustre mount failed: {e}", file=sys.stderr)
        return EXIT_ERROR
