"""Multi-node cluster management commands."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from .qemu_run import die, is_running, kill_qemu, run
from .vm_net import run_ssh, unregister_ssh_name
from .vm_state import (
    DEFAULT_TARGET,
    EXIT_TIMEOUT,
    ROOT_PASSWORD,
    SOCKETS,
    ClusterInfo,
    ClusterNode,
    ClusterNotFound,
    VMInfo,
    VMNotFound,
    lustre_libdir,
)


def parse_node_spec(spec: str) -> ClusterNode:
    """Parse a node spec like 'mgs+mds:myvm:1' or 'oss:myoss:3'.

    Format: roles:vmname[:diskcount]
    """
    parts = spec.split(":")
    if len(parts) < 2:
        die(f"invalid node spec '{spec}': need roles:name[:disks]")

    roles_str = parts[0]
    name = parts[1]
    # Validate the node name shares the same restrictions cmd_create
    # enforces -- spaces or special chars would break /etc/hosts /
    # SSH config / hostname / fc_name= cmdline.
    from .vm_commands import _validate_vm_name

    _validate_vm_name(name)
    if len(parts) > 2:
        try:
            disk_count = int(parts[2])
        except ValueError:
            die(
                f"invalid disk count '{parts[2]}' in spec '{spec}': "
                f"must be a non-negative integer (format: roles:name[:disks])"
            )
    else:
        disk_count = 0

    roles = roles_str.lower().split("+")
    for r in roles:
        if r not in ("mgs", "mds", "oss", "client"):
            die(f"unknown role '{r}' in spec '{spec}'")

    mdt_disks = 0
    ost_disks = 0
    if "mds" in roles:
        mdt_disks = max(disk_count, 1)
    if "oss" in roles:
        ost_disks = max(disk_count, 1)

    return ClusterNode(
        name=name,
        roles=roles,
        mdt_disks=mdt_disks,
        ost_disks=ost_disks,
    )


def generate_local_sh(cluster: ClusterInfo, os_family: str = "rhel") -> str:
    """Generate cfg/local.sh content for a multi-node cluster."""
    mgs = cluster.mgs_node()
    mds_list = cluster.mds_nodes()
    oss_list = cluster.oss_nodes()
    client_list = cluster.client_nodes()

    lustre_dir = lustre_libdir(os_family)
    lines = [
        f"# Cluster: {cluster.name}",
        "# Generated by ltvm cluster deploy",
        "",
        "FSNAME=lustre",
        "NETTYPE=tcp",
        "",
        f"LUSTRE={lustre_dir}",
        f"RLUSTRE={lustre_dir}",
        f"RPWD={lustre_dir}/tests",
        "",
    ]

    lines.append(f"mgs_HOST={mgs.name}")
    lines.append(f"MGSNID={mgs.ip}@tcp")

    combined = mgs.is_mds
    if not combined:
        lines.append("MGSDEV=/dev/vdb")
    lines.append("")

    if mds_list:
        lines.append(f"mds_HOST={mds_list[0].name}")
        total_mdts = sum(n.mdt_disks for n in mds_list)
        lines.append(f"MDSCOUNT={total_mdts}")

        mdt_idx = 1
        for mds_node in mds_list:
            # MDS disks always start at /dev/vdb on the MDS node.  If
            # MGS+MDS share a node (`combined`), no separate MGS disk
            # exists.  If they don't share, the MGS disk lives on the
            # MGS node, not on this MDS node, so no offset is needed
            # here either.
            disk_offset = 1

            for d in range(mds_node.mdt_disks):
                letter = chr(ord("a") + disk_offset + d)
                lines.append(f"MDSDEV{mdt_idx}=/dev/vd{letter}")
                if len(mds_list) > 1:
                    lines.append(
                        f"mds{mdt_idx}_HOST={mds_node.name}",
                    )
                mdt_idx += 1
        lines.append("")

    if oss_list:
        lines.append(f"ost_HOST={oss_list[0].name}")
        total_osts = sum(n.ost_disks for n in oss_list)
        lines.append(f"OSTCOUNT={total_osts}")

        ost_idx = 1
        for oss_node in oss_list:
            disk_offset = 1
            if oss_node.is_mgs and not oss_node.is_mds:
                disk_offset = 2
            if oss_node.is_mds:
                # If this OSS node is also the MDS, OST disks come
                # after the MDT disks.  Note: an OSS+MDS+MGS node has
                # `combined=True` (mgs.is_mds is True for it), so the
                # extra-MGS-disk offset only applies in the standalone
                # MGS case which lives on a different node entirely.
                disk_offset = 1 + oss_node.mdt_disks

            for d in range(oss_node.ost_disks):
                letter = chr(ord("a") + disk_offset + d)
                lines.append(f"OSTDEV{ost_idx}=/dev/vd{letter}")
                if len(oss_list) > 1:
                    lines.append(
                        f"ost{ost_idx}_HOST={oss_node.name}",
                    )
                ost_idx += 1
        lines.append("")

    if client_list:
        client_names = ",".join(n.name for n in client_list)
        lines.append(f"CLIENTS={client_names}")
    lines.append("")

    lines.append("FSTYPE=ldiskfs")
    lines.append("OSTSEQWIDTH=${OSTSEQWIDTH:-0x20000}")
    lines.append("")

    lines.append("LCTL=/usr/sbin/lctl")
    lines.append("LFS=/usr/bin/lfs")
    lines.append("")

    lines.append('PDSH="pdsh -S -Rssh -w"')
    lines.append("LOAD_MODULES_REMOTE=true")
    lines.append("MOUNT=/mnt/lustre")
    lines.append("MOUNT2=/mnt/lustre2")
    lines.append("")

    return "\n".join(lines) + "\n"


# ── cluster commands ─────────────────────────────────────


def _create_one_node(
    node: ClusterNode,
    vcpus: int,
    mem: int | None,
    os_target: str | None = None,
    arch: str | None = None,
    disk_size: str | None = None,
) -> tuple[str, int, str]:
    """Create a single cluster VM via ltvm subprocess.

    Returns (node_name, returncode, combined_output).
    Running via subprocess avoids threading issues with shared print/state
    inside cmd_create, and lets all nodes boot concurrently.

    `mem=None` means "let the inner cmd_create resolve from the target's
    default_mem", so cluster nodes inherit the per-target memory default
    instead of being silently overridden by a hardcoded constant in the
    cluster CLI parser.
    """
    mgs_disk = 1 if (node.is_mgs and not node.is_mds) else 0
    cmd = [
        "sudo",
        "ltvm",
        "create",
        node.name,
        "--vcpus",
        str(vcpus),
    ]
    if mem is not None:
        cmd += ["--mem", str(mem)]
    if os_target:
        cmd += ["--os", os_target]
    if arch:
        cmd += ["--arch", arch]
    if disk_size:
        cmd += ["--disk-size", disk_size]
    if node.mdt_disks + mgs_disk:
        cmd += ["--mdt-disks", str(node.mdt_disks + mgs_disk)]
    if node.ost_disks:
        cmd += ["--ost-disks", str(node.ost_disks)]

    # 300s: cold boot + disk creation + first-boot SSH wait (the inner
    # `ltvm create` already enforces SSH_TIMEOUT, but we leave headroom
    # for slow hosts and large disk allocations).
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    except subprocess.TimeoutExpired as e:
        # See _write_cluster_local_sh: don't propagate out of the parallel
        # executor; report the failure via the (name, rc, output) tuple
        # so the cluster create driver can summarise per-node failures.
        return node.name, 1, f"create timed out after {e.timeout}s"
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node.name, r.returncode, combined.rstrip("\n")


def cmd_cluster_create(args: argparse.Namespace) -> None:
    cluster_name = args.name
    if (SOCKETS / f"{cluster_name}.cluster").exists():
        die(f"cluster '{cluster_name}' already exists")

    node_specs = [parse_node_spec(s) for s in args.nodes]

    mgs_count = sum(1 for n in node_specs if n.is_mgs)
    if mgs_count == 0:
        die("cluster needs at least one node with mgs role")
    if mgs_count > 1:
        die("cluster can only have one MGS node")

    if not any(n.is_mds for n in node_specs):
        die("cluster needs at least one node with mds role")

    vcpus = args.vcpus
    mem = args.mem
    os_target = getattr(args, "os", None)
    arch = getattr(args, "arch", None)
    disk_size = getattr(args, "disk_size", None)

    print(f"=== Creating cluster '{cluster_name}' ===")
    if os_target:
        print(f"    Target: {os_target}{(' arch=' + arch) if arch else ''}")
    print(f"    Creating {len(node_specs)} nodes in parallel...")

    failed = []
    with ThreadPoolExecutor(max_workers=len(node_specs)) as executor:
        futures = {
            executor.submit(
                _create_one_node,
                node,
                vcpus,
                mem,
                os_target,
                arch,
                disk_size,
            ): node
            for node in node_specs
        }
        for future in as_completed(futures):
            node = futures[future]
            try:
                name, rc, output = future.result()
            except Exception as e:
                # Don't let one node's exception (e.g. TimeoutExpired
                # from the inner subprocess) abandon the remaining
                # futures.  Mark this one as failed and keep
                # collecting -- the cleanup loop below needs an
                # accurate `failed` list.
                name = node.name
                rc = -1
                output = f"exception: {type(e).__name__}: {e}"
            if rc != 0:
                print(f"\n--- {name}: FAILED (rc={rc}) ---\n{output}")
                failed.append(name)
            else:
                print(f"  {name}: up")

    if failed:
        # Clean up ALL nodes, including the failed ones.  A failed
        # `ltvm create` may have already created the TAP, overlay,
        # and .info file before erroring out (e.g. SSH wait timed out
        # so the rollback in cmd_create couldn't run).  `ltvm destroy`
        # is idempotent on missing VMs, so it's safe to call on every
        # node and necessary to avoid leaking partial state.
        for node in node_specs:
            r = subprocess.run(
                ["sudo", "ltvm", "destroy", node.name],
                capture_output=True,
            )
            if r.returncode != 0:
                print(
                    f"warning: failed to destroy VM '{node.name}' during cleanup",
                    file=sys.stderr,
                )
        die(f"vm create failed for: {', '.join(failed)}")

    # Load IPs now that all VMs are running
    for node in node_specs:
        vm = VMInfo.load(node.name)
        node.ip = vm.ip

    cluster = ClusterInfo(
        name=cluster_name,
        nodes=[
            {
                "name": n.name,
                "roles": n.roles,
                "mdt_disks": n.mdt_disks,
                "ost_disks": n.ost_disks,
                "ip": n.ip,
            }
            for n in node_specs
        ],
    )
    cluster.save()

    print(f"\n=== Cluster '{cluster_name}' created ===")
    for n in node_specs:
        print(f"  {n.name:<20} {n.ip:<18} {'+'.join(n.roles)}")
    print(
        f"\nNext: ltvm cluster deploy {cluster_name} "
        f"--build /path/to/lustre-release [--mount]"
    )


def _deploy_one_node(
    node_name: str,
    lustre_tree: str | Path,
    os_family: str = "rhel",
) -> tuple[str, int, str]:
    """Deploy Lustre to one cluster node.

    Returns (node_name, returncode, output_message).

    `lustre_tree` is the source tree the cluster's `--build` was
    pointed at; it determines where the per-tree staging dir lives.
    """
    from ltvm_pkg.deploy import deploy_to_vm
    from ltvm_pkg.lustre_build import staging_path as _staging_path

    vm = VMInfo.load(node_name)
    target = vm.os_id or DEFAULT_TARGET
    # Pass vm.arch + kernel so the staging dir matches what
    # build-lustre wrote.  Staging is keyed per-kernel so two kernels'
    # userland can coexist under one lustre tree.
    vm_arch = vm.arch or "x86_64"
    deploy_kernel: str | None = None
    if vm.kernel:
        vm_kernel_name = Path(vm.kernel).parent.name
        if vm_kernel_name:
            deploy_kernel = vm_kernel_name
    staging = _staging_path(
        lustre_tree, target, arch=vm_arch, kernel=deploy_kernel
    )
    if not staging.is_dir():
        legacy = _staging_path(lustre_tree, target, arch=vm_arch, kernel=None)
        if legacy.is_dir():
            staging = legacy
    try:
        deploy_to_vm(vm, staging, os_family=os_family)
        return node_name, 0, "ok"
    except RuntimeError as e:
        return node_name, 1, str(e)


def _write_cluster_local_sh(
    node_name: str,
    node_ip: str,
    local_sh: str,
    ssh_opts: list[str],
    os_family: str = "rhel",
) -> tuple[str, int, str]:
    """Write cluster local.sh to the standard test location on a node.

    Returns (node_name, returncode, output).
    """
    lustre_dir = lustre_libdir(os_family)
    cfg_path = f"{lustre_dir}/tests/cfg/local.sh"
    try:
        r = subprocess.run(
            ["sshpass", "-p", ROOT_PASSWORD, "ssh"]
            + ssh_opts
            + [
                f"root@{node_ip}",
                f"mkdir -p {lustre_dir}/tests/cfg && cat > {cfg_path}",
            ],
            input=local_sh,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except subprocess.TimeoutExpired as e:
        # Don't propagate out of the parallel executor; the caller checks
        # the returncode field and reports per-node failures.  Without
        # this catch, one stalled node tracebacks out of future.result()
        # and aborts the cluster config rollout mid-flight.
        return node_name, 1, f"timed out after {e.timeout}s writing {cfg_path}"
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node_name, r.returncode, combined.rstrip("\n")


def _validate_lustre_source(path: Path) -> None:
    """Die with a clear message if path is not a Lustre source tree.

    Only checks that the directory looks like a Lustre tree.
    Cluster deploy runs `ltvm build-lustre` itself, so a freshly
    cloned tree (no .ko files yet) is valid input.
    """
    if not path.is_dir():
        die(f"--build:'{path}' is not a directory")

    missing = [
        name
        for name in ("configure.ac", "lustre", "lnet")
        if not (path / name).exists()
    ]
    if missing:
        die(
            f"--build:'{path}' does not look like a Lustre "
            f"source tree (missing: {', '.join(missing)})"
        )


def cmd_cluster_deploy(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()
    src = Path(args.lustre_source).expanduser().resolve()
    _validate_lustre_source(src)
    build = str(src)

    # --server-only only affects the llmount.sh invocation, which only
    # runs when --mount is set.  Reject the combination instead of
    # silently dropping the flag.
    if getattr(args, "server_only", False) and not getattr(
        args, "mount", False
    ):
        die("--server-only requires --mount")

    # Derive os_family and target+kernel+arch from the first node's
    # metadata (all nodes in a cluster share the same target).  We also
    # pull the kernel name and arch off the VM so build-lustre uses the
    # right kernel tree and arch -- not just the target's defaults.
    os_family = "rhel"
    target = DEFAULT_TARGET
    kernel_name: str | None = None
    arch: str = "x86_64"
    try:
        first_vm = VMInfo.load(nodes[0].name)
    except (VMNotFound, IndexError) as e:
        die(f"cluster {cluster.name!r}: cannot load first node: {e}")
    if first_vm.os_id:
        from .target_config import TargetConfig

        target = first_vm.os_id
        # Let ValueError from TargetConfig propagate up with a clear
        # error.  Previously a broad `except (..., ValueError, ...): pass`
        # silently fell back to DEFAULT_TARGET, which deployed rocky9 .ko
        # files onto whatever the cluster actually ran.
        try:
            os_family = TargetConfig(
                target, arch=first_vm.arch or None
            ).os_family
        except ValueError as e:
            die(f"cluster {cluster.name!r}: target {target!r}: {e}")
    if first_vm.kernel:
        # vm.kernel points at .../kernels/<name>/vmlinuz; extract <name>
        kernel_name = Path(first_vm.kernel).parent.name
    if first_vm.arch:
        arch = first_vm.arch

    print(f"=== Deploying to cluster '{cluster.name}' ===")
    print(f"    Build: {build}")

    # Build Lustre from source before deploying.  All nodes share the
    # same target+kernel+arch, so we run build-lustre once and every
    # node rsyncs from the same staging dir.
    build_cmd = ["ltvm", "build-lustre", target, "--lustre-tree", build]
    if kernel_name:
        build_cmd += ["--kernel", kernel_name]
    # Forward --arch unconditionally.  Comparing against the literal
    # "x86_64" is wrong for a target whose default arch is something
    # else -- see the matching cmd_deploy comment.
    build_cmd += ["--arch", arch]
    sudo_user = os.environ.get("SUDO_USER")
    if sudo_user:
        build_cmd = ["sudo", "-u", sudo_user] + build_cmd
    print(f"--- Building Lustre against {target} kernel tree...")
    rb = subprocess.run(build_cmd)
    if rb.returncode != 0:
        die(f"Lustre build failed (rc={rb.returncode})")

    print(f"    Deploying to {len(nodes)} nodes in parallel...")

    # Deploy to all nodes in parallel -- same as single-node deploy,
    # just run concurrently.
    failed = []
    with ThreadPoolExecutor(max_workers=len(nodes)) as executor:
        futures = {
            executor.submit(_deploy_one_node, node.name, build, os_family): node
            for node in nodes
        }
        for future in as_completed(futures):
            name, rc, output = future.result()
            if rc != 0:
                print(f"\n--- {name}: FAILED (rc={rc}) ---\n{output}")
                failed.append(name)
            else:
                print(f"  {name}: deployed")

    if failed:
        die(f"deploy failed for: {', '.join(failed)}")

    # Record successful deploys on each VMInfo so `ltvm list` shows
    # last_deploy/build_path/kver -- single-node cmd_deploy does this
    # at the end of its flow; cluster deploy was missing it.
    import time as _time

    _now = int(_time.time())
    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            vm.update_deploy(_now, build, vm.kver)
        except VMNotFound:
            pass

    # Overwrite single-node local.sh with the cluster topology config.
    local_sh = generate_local_sh(cluster, os_family=os_family)
    print("\n--- Distributing cluster config (local.sh)...")
    print(local_sh)

    ssh_opts = [
        "-o",
        "StrictHostKeyChecking=no",
        "-o",
        "UserKnownHostsFile=/dev/null",
        "-o",
        "LogLevel=ERROR",
    ]
    try:
        node_ips = {node.name: VMInfo.load(node.name).ip for node in nodes}
    except VMNotFound as e:
        die(f"cluster node missing: {e}")
    failed_sh = []
    with ThreadPoolExecutor(max_workers=len(nodes)) as executor:
        futures = {
            executor.submit(
                _write_cluster_local_sh,
                node.name,
                node_ips[node.name],
                local_sh,
                ssh_opts,
                os_family,
            ): node
            for node in nodes
        }
        for future in as_completed(futures):
            name, rc, output = future.result()
            if rc != 0:
                print(f"\n--- {name}: local.sh FAILED (rc={rc}) ---\n{output}")
                failed_sh.append(name)
            else:
                print(f"  {name}: local.sh written")

    if failed_sh:
        die(f"local.sh distribution failed for: {', '.join(failed_sh)}")

    if args.mount:
        print("=== Mounting Lustre filesystem ===")
        mgs = cluster.mgs_node()
        mgs_vm = VMInfo.load(mgs.name)

        lustre_dir = lustre_libdir(os_family)
        mount_cmd = (
            f"cd {lustre_dir}/tests && LUSTRE={lustre_dir} bash llmount.sh"
        )
        if args.server_only:
            mount_cmd += " --server-only"

        print(f"Running llmount.sh from {mgs.name}...")
        try:
            r = run(
                ["sshpass", "-p", ROOT_PASSWORD, "ssh"]
                + ssh_opts
                + [f"root@{mgs_vm.ip}", mount_cmd],
                capture_output=False,
                timeout=300,
            )
        except subprocess.TimeoutExpired as e:
            die(
                f"llmount.sh timed out after {e.timeout}s on {mgs.name}\n"
                f"  modules are deployed; check `ltvm dmesg {mgs.name}` and "
                f"`ltvm cluster exec {cluster.name} mds 'lctl dl'`"
            )
        if r.returncode != 0:
            die("llmount.sh failed")
        print("=== Lustre mounted ===")

    print(f"\n=== Cluster '{cluster.name}' deployed ===")


def cmd_cluster_destroy(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()

    # Use the same _destroy_vm_artifacts helper that single-node
    # cmd_destroy uses, so we don't drift from its cleanup list.
    # The previous inlined loop forgot to unlink the per-VM .info.lock
    # file (added in round 15), causing `ltvm doctor` to report orphan
    # info locks for every node after every cluster destroy.
    from .vm_commands import _destroy_vm_artifacts

    print(f"=== Destroying cluster '{cluster.name}' ===")
    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            kill_qemu(vm)
        except VMNotFound:
            pass

        _destroy_vm_artifacts(node.name)
        unregister_ssh_name(node.name)
        print(f"  destroyed {node.name}")

    cluster.path.unlink(missing_ok=True)
    print(f"=== Cluster '{cluster.name}' destroyed ===")


def cmd_cluster_list(args: argparse.Namespace) -> None:
    names = ClusterInfo.all_names()
    if not names:
        print("(no clusters)")
        return
    for cname in names:
        try:
            cluster = ClusterInfo.load(cname)
        except ClusterNotFound:
            # Race: .cluster file disappeared between all_names() and load().
            continue
        nodes = cluster.get_nodes()
        node_summary = []
        for n in nodes:
            roles = "+".join(n.roles)
            try:
                running = "up" if is_running(VMInfo.load(n.name)) else "down"
            except VMNotFound:
                running = "missing"
            node_summary.append(f"{n.name}({roles},{running})")
        print(f"{cname}: {' '.join(node_summary)}")


def cmd_cluster_status(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()

    print(f"cluster: {cluster.name}")
    print(f"nodes:   {len(nodes)}")
    print()

    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            running = is_running(vm)
        except VMNotFound:
            running = False

        status = "running" if running else "stopped"
        roles = "+".join(node.roles)
        disks = ""
        if node.mdt_disks:
            disks += f" mdt={node.mdt_disks}"
        if node.ost_disks:
            disks += f" ost={node.ost_disks}"
        if node.is_mgs and not node.is_mds:
            disks += " mgs=1"

        print(
            f"  {node.name:<20} {node.ip:<18} {status:<8} {roles:<12}{disks}",
        )


def cmd_cluster_ssh(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    target = args.target
    nodes = cluster.get_nodes()

    matched = next(
        (n for n in nodes if n.name == target or target in n.roles),
        None,
    )
    if matched is None:
        die(
            f"no node matching '{target}' in cluster '{args.name}'",
        )
        raise AssertionError("unreachable")

    vm = VMInfo.load(matched.name)
    ssh_args = [
        "sshpass",
        "-p",
        ROOT_PASSWORD,
        "ssh",
        "-o",
        "StrictHostKeyChecking=no",
        "-o",
        "UserKnownHostsFile=/dev/null",
        "-o",
        "LogLevel=ERROR",
        f"root@{vm.ip}",
    ] + args.command
    os.execvp("sshpass", ssh_args)


def cmd_cluster_exec(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    target = args.target
    nodes = cluster.get_nodes()

    matched = next(
        (n for n in nodes if n.name == target or target in n.roles),
        None,
    )
    if matched is None:
        die(
            f"no node matching '{target}' in cluster '{args.name}'",
        )
        raise AssertionError("unreachable")

    command = " ".join(args.command)
    vm = VMInfo.load(matched.name)
    try:
        r = run_ssh(vm.ip, command, timeout=args.timeout)
        if r.stdout:
            print(r.stdout, end="")
        if r.stderr:
            print(r.stderr, end="", file=sys.stderr)
        sys.exit(r.returncode)
    except subprocess.TimeoutExpired:
        die(f"timeout after {args.timeout}s", EXIT_TIMEOUT)
