"""Multi-node cluster management commands."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from .commands import cmd_create
from .models import (
    EXIT_TIMEOUT,
    OVERLAYS,
    SOCKETS,
    ClusterInfo,
    ClusterNode,
    VMInfo,
    VMNotFound,
)
from .net import run_ssh, unregister_ssh_name
from .process import die, is_running, kill_qemu, run


def parse_node_spec(spec: str) -> ClusterNode:
    """Parse a node spec like 'mgs+mds:myvm:1' or 'oss:myoss:3'.

    Format: roles:vmname[:diskcount]
    """
    parts = spec.split(":")
    if len(parts) < 2:
        die(f"invalid node spec '{spec}': need roles:name[:disks]")

    roles_str = parts[0]
    name = parts[1]
    disk_count = int(parts[2]) if len(parts) > 2 else 0

    roles = roles_str.lower().split("+")
    for r in roles:
        if r not in ("mgs", "mds", "oss", "client"):
            die(f"unknown role '{r}' in spec '{spec}'")

    mdt_disks = 0
    ost_disks = 0
    if "mds" in roles:
        mdt_disks = max(disk_count, 1)
    if "oss" in roles:
        ost_disks = max(disk_count, 1)

    return ClusterNode(
        name=name,
        roles=roles,
        mdt_disks=mdt_disks,
        ost_disks=ost_disks,
    )


def generate_local_sh(cluster: ClusterInfo) -> str:
    """Generate cfg/local.sh content for a multi-node cluster.

    Paths reference /usr/lib64/lustre, where deploy-lustre.sh always
    installs the test framework (same as single-node deploy).
    """
    mgs = cluster.mgs_node()
    mds_list = cluster.mds_nodes()
    oss_list = cluster.oss_nodes()
    client_list = cluster.client_nodes()

    lines = [
        f"# Cluster: {cluster.name}",
        "# Generated by vm.py cluster deploy",
        "",
        "FSNAME=lustre",
        "NETTYPE=tcp",
        "",
        "LUSTRE=/usr/lib64/lustre",
        "RLUSTRE=/usr/lib64/lustre",
        "RPWD=/usr/lib64/lustre/tests",
        "",
    ]

    lines.append(f"mgs_HOST={mgs.name}")
    lines.append(f"MGSNID={mgs.ip}@tcp")

    combined = mgs.is_mds
    if not combined:
        lines.append("MGSDEV=/dev/vdb")
    lines.append("")

    if mds_list:
        lines.append(f"mds_HOST={mds_list[0].name}")
        total_mdts = sum(n.mdt_disks for n in mds_list)
        lines.append(f"MDSCOUNT={total_mdts}")

        mdt_idx = 1
        for mds_node in mds_list:
            disk_offset = 1
            if mds_node.is_mgs and not combined:
                disk_offset = 2

            for d in range(mds_node.mdt_disks):
                letter = chr(ord("a") + disk_offset + d)
                lines.append(f"MDSDEV{mdt_idx}=/dev/vd{letter}")
                if len(mds_list) > 1:
                    lines.append(
                        f"mds{mdt_idx}_HOST={mds_node.name}",
                    )
                mdt_idx += 1
        lines.append("")

    if oss_list:
        lines.append(f"ost_HOST={oss_list[0].name}")
        total_osts = sum(n.ost_disks for n in oss_list)
        lines.append(f"OSTCOUNT={total_osts}")

        ost_idx = 1
        for oss_node in oss_list:
            disk_offset = 1
            if oss_node.is_mgs and not oss_node.is_mds:
                disk_offset = 2
            if oss_node.is_mds:
                disk_offset = 1 + oss_node.mdt_disks
                if oss_node.is_mgs and not combined:
                    disk_offset += 1

            for d in range(oss_node.ost_disks):
                letter = chr(ord("a") + disk_offset + d)
                lines.append(f"OSTDEV{ost_idx}=/dev/vd{letter}")
                if len(oss_list) > 1:
                    lines.append(
                        f"ost{ost_idx}_HOST={oss_node.name}",
                    )
                ost_idx += 1
        lines.append("")

    if client_list:
        client_names = ",".join(n.name for n in client_list)
        lines.append(f"CLIENTS={client_names}")
    lines.append("")

    lines.append("FSTYPE=ldiskfs")
    lines.append("OSTSEQWIDTH=${OSTSEQWIDTH:-0x20000}")
    lines.append("")

    lines.append("LCTL=/usr/sbin/lctl")
    lines.append("LFS=/usr/bin/lfs")
    lines.append("")

    lines.append('PDSH="pdsh -S -Rssh -w"')
    lines.append("LOAD_MODULES_REMOTE=true")
    lines.append("MOUNT=/mnt/lustre")
    lines.append("")

    return "\n".join(lines) + "\n"


# ── cluster commands ─────────────────────────────────────


def cmd_cluster(args: argparse.Namespace) -> None:
    """Dispatch cluster subcommands."""
    subcmd = args.cluster_cmd

    dispatch = {
        "create": cmd_cluster_create,
        "deploy": cmd_cluster_deploy,
        "destroy": cmd_cluster_destroy,
        "list": cmd_cluster_list,
        "status": cmd_cluster_status,
        "ssh": cmd_cluster_ssh,
        "exec": cmd_cluster_exec,
    }
    fn = dispatch.get(subcmd)
    if fn:
        fn(args)
    else:
        die(f"unknown cluster command: {subcmd}")


def cmd_cluster_create(args: argparse.Namespace) -> None:
    cluster_name = args.name
    if (SOCKETS / f"{cluster_name}.cluster").exists():
        die(f"cluster '{cluster_name}' already exists")

    node_specs = [parse_node_spec(s) for s in args.nodes]

    mgs_count = sum(1 for n in node_specs if n.is_mgs)
    if mgs_count == 0:
        die("cluster needs at least one node with mgs role")
    if mgs_count > 1:
        die("cluster can only have one MGS node")

    if not any(n.is_mds for n in node_specs):
        die("cluster needs at least one node with mds role")

    vcpus = args.vcpus
    mem = args.mem

    print(f"=== Creating cluster '{cluster_name}' ===")
    for node in node_specs:
        mdt = node.mdt_disks
        ost = node.ost_disks
        mgs_disk = 1 if (node.is_mgs and not node.is_mds) else 0

        print(
            f"--- Creating {node.name} ({'+'.join(node.roles)})...",
        )

        create_args = argparse.Namespace(
            name=node.name,
            vcpus=vcpus,
            mem=mem,
            ip=None,
            rootfs=None,
            image="",
            kernel="",
            mdt_disks=mdt + mgs_disk,
            ost_disks=ost,
        )
        cmd_create(create_args)

        vm = VMInfo.load(node.name)
        node.ip = vm.ip

    cluster = ClusterInfo(
        name=cluster_name,
        nodes=[
            {
                "name": n.name,
                "roles": n.roles,
                "mdt_disks": n.mdt_disks,
                "ost_disks": n.ost_disks,
                "ip": n.ip,
            }
            for n in node_specs
        ],
    )
    cluster.save()

    print(f"\n=== Cluster '{cluster_name}' created ===")
    for n in node_specs:
        print(f"  {n.name:<20} {n.ip:<18} {'+'.join(n.roles)}")
    print(
        f"\nNext: vm.py cluster deploy {cluster_name} "
        f"--build /path/to/lustre-release [--mount]"
    )


def _deploy_one_node(node_name: str, build: str) -> tuple[str, int, str]:
    """Deploy Lustre to one cluster node via deploy-lustre.sh.

    Returns (node_name, returncode, combined_output).
    """
    r = subprocess.run(
        ["sudo", "deploy-lustre.sh", "--vm", node_name, "--build", build],
        capture_output=True,
        text=True,
        timeout=300,
    )
    combined = r.stdout
    if r.stderr:
        combined = combined + r.stderr if combined else r.stderr
    return node_name, r.returncode, combined.rstrip("\n")


def _write_cluster_local_sh(
    node_ip: str, local_sh: str, ssh_opts: list[str]
) -> None:
    """Write cluster local.sh to the standard test location on a node."""
    cfg_path = "/usr/lib64/lustre/tests/cfg/local.sh"
    subprocess.run(
        ["sshpass", "-p", "initial0", "ssh"]
        + ssh_opts
        + [
            f"root@{node_ip}",
            f"mkdir -p /usr/lib64/lustre/tests/cfg && cat > {cfg_path}",
        ],
        input=local_sh,
        capture_output=True,
        text=True,
        timeout=10,
    )


def cmd_cluster_deploy(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()
    build = str(Path(args.build).resolve())

    if not Path(build).is_dir():
        die(f"build directory '{build}' not found")

    print(f"=== Deploying to cluster '{cluster.name}' ===")
    print(f"    Build: {build}")
    print(f"    Deploying to {len(nodes)} nodes in parallel...")

    # Deploy to all nodes in parallel using deploy-lustre.sh -- same
    # as single-node deploy, just run concurrently.
    failed = []
    with ThreadPoolExecutor(max_workers=len(nodes)) as executor:
        futures = {
            executor.submit(_deploy_one_node, node.name, build): node
            for node in nodes
        }
        for future in as_completed(futures):
            node = futures[future]
            name, rc, output = future.result()
            if rc != 0:
                print(f"\n--- {name}: FAILED (rc={rc}) ---\n{output}")
                failed.append(name)
            else:
                print(f"  {name}: deployed")

    if failed:
        die(f"deploy-lustre.sh failed for: {', '.join(failed)}")

    # Overwrite single-node local.sh with the cluster topology config.
    local_sh = generate_local_sh(cluster)
    print("\n--- Distributing cluster config (local.sh)...")
    print(local_sh)

    ssh_opts = [
        "-o",
        "StrictHostKeyChecking=no",
        "-o",
        "UserKnownHostsFile=/dev/null",
        "-o",
        "LogLevel=ERROR",
    ]
    for node in nodes:
        vm = VMInfo.load(node.name)
        _write_cluster_local_sh(vm.ip, local_sh, ssh_opts)
        print(f"  {node.name}: local.sh written")

    if args.mount:
        print("=== Mounting Lustre filesystem ===")
        mgs = cluster.mgs_node()
        mgs_vm = VMInfo.load(mgs.name)

        mount_cmd = (
            "cd /usr/lib64/lustre/tests"
            " && LUSTRE=/usr/lib64/lustre bash llmount.sh"
        )
        if args.server_only:
            mount_cmd += " --server-only"

        print(f"Running llmount.sh from {mgs.name}...")
        r = run(
            ["sshpass", "-p", "initial0", "ssh"]
            + ssh_opts
            + [f"root@{mgs_vm.ip}", mount_cmd],
            capture_output=False,
            timeout=300,
        )
        if r.returncode != 0:
            die("llmount.sh failed")
        print("=== Lustre mounted ===")

    print(f"\n=== Cluster '{cluster.name}' deployed ===")


def cmd_cluster_destroy(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()

    print(f"=== Destroying cluster '{cluster.name}' ===")
    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            kill_qemu(vm)
        except VMNotFound:
            pass

        overlay = OVERLAYS / f"{node.name}.qcow2"
        for f in [overlay] + list(
            OVERLAYS.glob(f"{node.name}-disk*.img"),
        ):
            f.unlink(missing_ok=True)
        for ext in ("sock", "pid", "info", "log"):
            (SOCKETS / f"{node.name}.{ext}").unlink(
                missing_ok=True,
            )
        unregister_ssh_name(node.name)
        print(f"  destroyed {node.name}")

    cluster.path.unlink(missing_ok=True)
    print(f"=== Cluster '{cluster.name}' destroyed ===")


def cmd_cluster_list(args: argparse.Namespace) -> None:
    names = ClusterInfo.all_names()
    if not names:
        print("(no clusters)")
        return
    for cname in names:
        cluster = ClusterInfo.load(cname)
        nodes = cluster.get_nodes()
        node_summary = []
        for n in nodes:
            roles = "+".join(n.roles)
            running = "up" if is_running(VMInfo.load(n.name)) else "down"
            node_summary.append(f"{n.name}({roles},{running})")
        print(f"{cname}: {' '.join(node_summary)}")


def cmd_cluster_status(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    nodes = cluster.get_nodes()

    print(f"cluster: {cluster.name}")
    print(f"nodes:   {len(nodes)}")
    print()

    for node in nodes:
        try:
            vm = VMInfo.load(node.name)
            running = is_running(vm)
        except VMNotFound:
            running = False

        status = "running" if running else "stopped"
        roles = "+".join(node.roles)
        disks = ""
        if node.mdt_disks:
            disks += f" mdt={node.mdt_disks}"
        if node.ost_disks:
            disks += f" ost={node.ost_disks}"
        if node.is_mgs and not node.is_mds:
            disks += " mgs=1"

        print(
            f"  {node.name:<20} {node.ip:<18} {status:<8} {roles:<12}{disks}",
        )


def cmd_cluster_ssh(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    target = args.target
    nodes = cluster.get_nodes()

    found = None
    for n in nodes:
        if n.name == target or target in n.roles:
            found = n
            break
    if not found:
        die(
            f"no node matching '{target}' in cluster '{args.name}'",
        )

    vm = VMInfo.load(found.name)
    ssh_args = [
        "sshpass",
        "-p",
        "initial0",
        "ssh",
        "-o",
        "StrictHostKeyChecking=no",
        "-o",
        "LogLevel=ERROR",
        f"root@{vm.ip}",
    ] + args.command
    os.execvp("sshpass", ssh_args)


def cmd_cluster_exec(args: argparse.Namespace) -> None:
    cluster = ClusterInfo.load(args.name)
    target = args.target
    nodes = cluster.get_nodes()

    found = None
    for n in nodes:
        if n.name == target or target in n.roles:
            found = n
            break
    if not found:
        die(
            f"no node matching '{target}' in cluster '{args.name}'",
        )

    command = " ".join(args.command)
    vm = VMInfo.load(found.name)
    try:
        r = run_ssh(vm.ip, command, timeout=args.timeout)
        if r.stdout:
            print(r.stdout, end="")
        sys.exit(r.returncode)
    except subprocess.TimeoutExpired:
        die(f"timeout after {args.timeout}s", EXIT_TIMEOUT)
